package net.packages.flying_machines.entity.animation;

import net.minecraft.client.render.entity.animation.Animation;
import net.minecraft.client.render.entity.animation.AnimationHelper;
import net.minecraft.client.render.entity.animation.Keyframe;
import net.minecraft.client.render.entity.animation.Transformation;

public class Animations {

	public static final Animation LOOKINGAROUND = Animation.Builder.create(3.25f)
			.addBoneAnimation("body",
									  new Transformation(Transformation.Targets.TRANSLATE,
		new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
	Transformation.Interpolations.CUBIC),
			new Keyframe(0.5f, AnimationHelper.createTranslationalVector(0f, 0.1f, 0f),
	Transformation.Interpolations.CUBIC),
			new Keyframe(0.75f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
	Transformation.Interpolations.CUBIC)))
			.addBoneAnimation("head",
									  new Transformation(Transformation.Targets.TRANSLATE,
		new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
	Transformation.Interpolations.LINEAR),
			new Keyframe(1.125f, AnimationHelper.createTranslationalVector(0f, 0.2f, 0f),
	Transformation.Interpolations.LINEAR),
			new Keyframe(1.5416767f, AnimationHelper.createTranslationalVector(0f, 0.7f, 0f),
	Transformation.Interpolations.CUBIC),
			new Keyframe(2.7916765f, AnimationHelper.createTranslationalVector(0f, 0.2f, 0f),
	Transformation.Interpolations.CUBIC),
			new Keyframe(3f, AnimationHelper.createTranslationalVector(0f, -0.1f, 0f),
	Transformation.Interpolations.CUBIC),
			new Keyframe(3.25f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
	Transformation.Interpolations.CUBIC)))
			.addBoneAnimation("head",
									  new Transformation(Transformation.Targets.ROTATE,
		new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
	Transformation.Interpolations.LINEAR),
			new Keyframe(0.75f, AnimationHelper.createRotationalVector(12.5f, 0f, 0f),
	Transformation.Interpolations.CUBIC),
			new Keyframe(1.125f, AnimationHelper.createRotationalVector(10.02f, 4.95f, 0.76f),
	Transformation.Interpolations.CUBIC),
			new Keyframe(1.5416767f, AnimationHelper.createRotationalVector(12.52f, 4.95f, 0.76f),
	Transformation.Interpolations.CUBIC),
			new Keyframe(2f, AnimationHelper.createRotationalVector(12.77f, 12.27f, 2.42f),
	Transformation.Interpolations.CUBIC),
			new Keyframe(2.25f, AnimationHelper.createRotationalVector(13.24f, 19.48f, 4.15f),
	Transformation.Interpolations.CUBIC),
			new Keyframe(2.5834335f, AnimationHelper.createRotationalVector(10.4f, 14.61f, 2.97f),
	Transformation.Interpolations.CUBIC),
			new Keyframe(3.25f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
	Transformation.Interpolations.CUBIC)))
			.addBoneAnimation("lefthand",
									  new Transformation(Transformation.Targets.ROTATE,
		new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
	Transformation.Interpolations.LINEAR),
			new Keyframe(0.75f, AnimationHelper.createRotationalVector(-22.99f, 11.53f, -4.85f),
	Transformation.Interpolations.LINEAR),
			new Keyframe(1.4583433f, AnimationHelper.createRotationalVector(-42.38f, 0.46f, 0.98f),
	Transformation.Interpolations.CUBIC),
			new Keyframe(1.75f, AnimationHelper.createRotationalVector(-44.88f, 0.46f, 0.98f),
	Transformation.Interpolations.CUBIC),
			new Keyframe(2.0834335f, AnimationHelper.createRotationalVector(-44.92f, 2.23f, -0.78f),
	Transformation.Interpolations.CUBIC),
			new Keyframe(2.2916765f, AnimationHelper.createRotationalVector(-44.89f, -1.32f, 2.75f),
	Transformation.Interpolations.CUBIC),
			new Keyframe(2.6766665f, AnimationHelper.createRotationalVector(-34.88f, 0.73f, 0.71f),
	Transformation.Interpolations.CUBIC),
			new Keyframe(2.7916765f, AnimationHelper.createRotationalVector(-27.46f, -3.09f, 4.51f),
	Transformation.Interpolations.CUBIC),
			new Keyframe(3.25f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
	Transformation.Interpolations.CUBIC)))
			.addBoneAnimation("leftleg",
									  new Transformation(Transformation.Targets.TRANSLATE,
		new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
	Transformation.Interpolations.LINEAR),
			new Keyframe(0.5f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
	Transformation.Interpolations.LINEAR),
			new Keyframe(3.25f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
	Transformation.Interpolations.CUBIC)))
			.addBoneAnimation("leftleg",
									  new Transformation(Transformation.Targets.ROTATE,
		new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
	Transformation.Interpolations.LINEAR),
			new Keyframe(0.375f, AnimationHelper.createRotationalVector(0.22f, -5f, -2.51f),
	Transformation.Interpolations.CUBIC),
			new Keyframe(1.0834333f, AnimationHelper.createRotationalVector(-2.28f, -5f, -2.51f),
	Transformation.Interpolations.CUBIC),
			new Keyframe(1.625f, AnimationHelper.createRotationalVector(-2.31f, -9.99f, -2.31f),
	Transformation.Interpolations.CUBIC),
			new Keyframe(2.8343335f, AnimationHelper.createRotationalVector(-2.28f, -5f, -2.51f),
	Transformation.Interpolations.CUBIC),
			new Keyframe(3.25f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
	Transformation.Interpolations.CUBIC)))
			.addBoneAnimation("rightleg",
									  new Transformation(Transformation.Targets.TRANSLATE,
		new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
	Transformation.Interpolations.LINEAR),
			new Keyframe(0.5f, AnimationHelper.createTranslationalVector(0f, 0.2f, 0f),
	Transformation.Interpolations.LINEAR),
			new Keyframe(3.25f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
	Transformation.Interpolations.CUBIC)))
			.addBoneAnimation("rightleg",
									  new Transformation(Transformation.Targets.ROTATE,
		new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
	Transformation.Interpolations.LINEAR),
			new Keyframe(0.375f, AnimationHelper.createRotationalVector(0.22f, 5f, 2.51f),
	Transformation.Interpolations.CUBIC),
			new Keyframe(1.0834333f, AnimationHelper.createRotationalVector(2.72f, 5f, 2.51f),
	Transformation.Interpolations.CUBIC),
			new Keyframe(1.625f, AnimationHelper.createRotationalVector(2.71f, 2.5f, 2.39f),
	Transformation.Interpolations.CUBIC),
			new Keyframe(2.8343335f, AnimationHelper.createRotationalVector(-2.29f, -2.5f, 2.59f),
	Transformation.Interpolations.CUBIC),
			new Keyframe(3.25f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
	Transformation.Interpolations.CUBIC)))
			.addBoneAnimation("righthand",
									  new Transformation(Transformation.Targets.ROTATE,
		new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
	Transformation.Interpolations.CUBIC),
			new Keyframe(1f, AnimationHelper.createRotationalVector(-28.42f, -6.25f, 3.98f),
	Transformation.Interpolations.CUBIC),
			new Keyframe(1.4583433f, AnimationHelper.createRotationalVector(-65.7f, 1.87f, -1.87f),
	Transformation.Interpolations.CUBIC),
			new Keyframe(1.75f, AnimationHelper.createRotationalVector(-72.46f, 7f, -18.27f),
	Transformation.Interpolations.CUBIC),
			new Keyframe(1.9583433f, AnimationHelper.createRotationalVector(-72.6f, -0.16f, -20.53f),
	Transformation.Interpolations.CUBIC),
			new Keyframe(2.125f, AnimationHelper.createRotationalVector(-85.1f, -0.16f, -20.53f),
	Transformation.Interpolations.CUBIC),
			new Keyframe(2.3433335f, AnimationHelper.createRotationalVector(-84.93f, 12.26f, -19.11f),
	Transformation.Interpolations.CUBIC),
			new Keyframe(2.5416765f, AnimationHelper.createRotationalVector(-69.81f, 17.24f, -18.65f),
	Transformation.Interpolations.CUBIC),
			new Keyframe(2.75f, AnimationHelper.createRotationalVector(-33.2f, 6.03f, -1.23f),
	Transformation.Interpolations.CUBIC),
			new Keyframe(2.875f, AnimationHelper.createRotationalVector(-30.14f, 4.75f, 0.69f),
	Transformation.Interpolations.CUBIC),
			new Keyframe(3f, AnimationHelper.createRotationalVector(-25.14f, 4.75f, 0.69f),
	Transformation.Interpolations.CUBIC),
			new Keyframe(3.25f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
	Transformation.Interpolations.CUBIC)))
			.addBoneAnimation("head_eye",
									  new Transformation(Transformation.Targets.TRANSLATE,
		new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0.25f),
	Transformation.Interpolations.LINEAR),
			new Keyframe(3.25f, AnimationHelper.createTranslationalVector(0f, 0f, 0.25f),
	Transformation.Interpolations.LINEAR))).build();
	public static final Animation WALK = Animation.Builder.create(1.5f).looping()
			.addBoneAnimation("body",
					new Transformation(Transformation.Targets.TRANSLATE,
							new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, -0.1f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.5f, AnimationHelper.createTranslationalVector(0f, 0.2f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(1f, AnimationHelper.createTranslationalVector(0f, -0.1f, 0f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("head",
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0f, AnimationHelper.createRotationalVector(7.5f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.75f, AnimationHelper.createRotationalVector(-1f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(1.5f, AnimationHelper.createRotationalVector(7.5f, 0f, 0f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("headphone",
					new Transformation(Transformation.Targets.TRANSLATE,
							new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.25f, AnimationHelper.createTranslationalVector(0f, 0.25f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.5f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(1f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("leftleg",
					new Transformation(Transformation.Targets.TRANSLATE,
							new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0.1f, 0.3f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(0.25f, AnimationHelper.createTranslationalVector(0f, 0.02f, -0.09f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(0.5f, AnimationHelper.createTranslationalVector(0f, -0.72f, -0.76f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(0.75f, AnimationHelper.createTranslationalVector(0f, -0.7f, -1.2f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(1f, AnimationHelper.createTranslationalVector(0f, -0.17f, -0.77f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(1.25f, AnimationHelper.createTranslationalVector(0f, -0.01f, -0.18f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(1.5f, AnimationHelper.createTranslationalVector(0f, 0.1f, 0.3f),
									Transformation.Interpolations.CUBIC)))
			.addBoneAnimation("leftleg",
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0f, AnimationHelper.createRotationalVector(20.02f, -2.35f, -0.86f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(0.75f, AnimationHelper.createRotationalVector(-32.52f, -2.11f, 1.34f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(1.5f, AnimationHelper.createRotationalVector(20.02f, -2.35f, -0.86f),
									Transformation.Interpolations.CUBIC)))
			.addBoneAnimation("rightleg",
					new Transformation(Transformation.Targets.TRANSLATE,
							new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, -0.15f, -0.3f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(0.25f, AnimationHelper.createTranslationalVector(0f, 0.1f, -0.26f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(0.5f, AnimationHelper.createTranslationalVector(0f, 0.27f, -0.17f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(0.75f, AnimationHelper.createTranslationalVector(0f, 0.35f, -0.1f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(1f, AnimationHelper.createTranslationalVector(0f, 0.62f, -0.16f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(1.5f, AnimationHelper.createTranslationalVector(0f, -0.15f, -0.3f),
									Transformation.Interpolations.CUBIC)))
			.addBoneAnimation("rightleg",
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0f, AnimationHelper.createRotationalVector(-20.13f, 2.35f, -0.86f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(0.75f, AnimationHelper.createRotationalVector(22.52f, 2.31f, 0.96f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(1.5f, AnimationHelper.createRotationalVector(-20.13f, 2.35f, -0.86f),
									Transformation.Interpolations.CUBIC)))
			.addBoneAnimation("lefthand",
					new Transformation(Transformation.Targets.TRANSLATE,
							new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.75f, AnimationHelper.createTranslationalVector(0f, -0.5f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(1.5f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("lefthand",
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0f, AnimationHelper.createRotationalVector(-15f, 0f, 0f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(0.75f, AnimationHelper.createRotationalVector(17f, 0f, 0f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(1.5f, AnimationHelper.createRotationalVector(-15f, 0f, 0f),
									Transformation.Interpolations.CUBIC)))
			.addBoneAnimation("righthand",
					new Transformation(Transformation.Targets.TRANSLATE,
							new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.75f, AnimationHelper.createTranslationalVector(0f, -0.5f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(1.5f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("righthand",
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0f, AnimationHelper.createRotationalVector(15f, 0f, 0f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(0.75f, AnimationHelper.createRotationalVector(-19.5f, 0f, 0f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(1.5f, AnimationHelper.createRotationalVector(15f, 0f, 0f),
									Transformation.Interpolations.CUBIC)))
			.addBoneAnimation("dylan",
					new Transformation(Transformation.Targets.TRANSLATE,
							new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0.25f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(1.5f, AnimationHelper.createTranslationalVector(0f, 0.25f, 0f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("torso",
					new Transformation(Transformation.Targets.TRANSLATE,
							new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, -0.5f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.3433333f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.75f, AnimationHelper.createTranslationalVector(0f, -0.5f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(1.1676667f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(1.5f, AnimationHelper.createTranslationalVector(0f, -0.5f, 0f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("head_eye",
					new Transformation(Transformation.Targets.TRANSLATE,
							new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0.25f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(1.5f, AnimationHelper.createTranslationalVector(0f, 0f, 0.25f),
									Transformation.Interpolations.LINEAR))).build();
	public static final Animation IDLE = Animation.Builder.create(1.2916767f).looping()
			.addBoneAnimation("head",
					new Transformation(Transformation.Targets.TRANSLATE,
							new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(0.5f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(1.2916767f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.CUBIC)))
			.addBoneAnimation("head",
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(0.5f, AnimationHelper.createRotationalVector(-2.5f, 0f, 0f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(1.2916767f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
									Transformation.Interpolations.CUBIC)))
			.addBoneAnimation("headphone",
					new Transformation(Transformation.Targets.TRANSLATE,
							new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("lefthand",
					new Transformation(Transformation.Targets.TRANSLATE,
							new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(0.5f, AnimationHelper.createTranslationalVector(0f, 0.3f, 0f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(1.25f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.CUBIC)))
			.addBoneAnimation("lefthand",
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0f, AnimationHelper.createRotationalVector(0.33f, -7.49f, -2.52f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.5f, AnimationHelper.createRotationalVector(-2.17f, -7.49f, -2.52f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(1.25f, AnimationHelper.createRotationalVector(0.33f, -7.49f, -2.52f),
									Transformation.Interpolations.CUBIC)))
			.addBoneAnimation("righthand",
					new Transformation(Transformation.Targets.TRANSLATE,
							new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.5f, AnimationHelper.createTranslationalVector(0f, 0.3f, 0f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(1.2916767f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("righthand",
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0f, AnimationHelper.createRotationalVector(0.66f, 7.47f, 5.04f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.5f, AnimationHelper.createRotationalVector(3.16f, 7.47f, 5.04f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(1.2916767f, AnimationHelper.createRotationalVector(0.66f, 7.47f, 5.04f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("rightleg",
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0f, AnimationHelper.createRotationalVector(0.22f, 5f, 2.51f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(0.875f, AnimationHelper.createRotationalVector(0.22f, 5f, 2.51f),
									Transformation.Interpolations.CUBIC)))
			.addBoneAnimation("leftleg",
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0f, AnimationHelper.createRotationalVector(0f, -5f, 0f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(0.875f, AnimationHelper.createRotationalVector(0f, -5f, 0f),
									Transformation.Interpolations.CUBIC)))
			.addBoneAnimation("torso",
					new Transformation(Transformation.Targets.TRANSLATE,
							new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.5f, AnimationHelper.createTranslationalVector(0f, 0.25f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(1.2916767f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("torso",
					new Transformation(Transformation.Targets.SCALE,
							new Keyframe(0f, AnimationHelper.createScalingVector(1f, 1f, 1f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.5f, AnimationHelper.createScalingVector(1f, 1f, 1f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(1.2916767f, AnimationHelper.createScalingVector(1f, 1f, 1f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("head_eye",
					new Transformation(Transformation.Targets.TRANSLATE,
							new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0.25f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(1.2916767f, AnimationHelper.createTranslationalVector(0f, 0f, 0.25f),
									Transformation.Interpolations.LINEAR))).build();
	public static final Animation ATTACK = Animation.Builder.create(2f).looping()
			.addBoneAnimation("dylan",
					new Transformation(Transformation.Targets.TRANSLATE,
							new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(2f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(4f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.CUBIC)))
			.addBoneAnimation("dylan",
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(1f, AnimationHelper.createRotationalVector(0f, 2.5f, 0f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(2f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
									Transformation.Interpolations.CUBIC)))
			.addBoneAnimation("head",
					new Transformation(Transformation.Targets.TRANSLATE,
							new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0.05f, 0f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(0.5834334f, AnimationHelper.createTranslationalVector(0f, 0.05f, 0f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(2f, AnimationHelper.createTranslationalVector(0f, 0.05f, 0f),
									Transformation.Interpolations.CUBIC)))
			.addBoneAnimation("head",
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0f, AnimationHelper.createRotationalVector(0.5f, -4.99f, 0.17f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(0.75f, AnimationHelper.createRotationalVector(3f, -2.49f, 0.2f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(1.1676667f, AnimationHelper.createRotationalVector(7.45f, -0.53f, 0.52f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(2f, AnimationHelper.createRotationalVector(0.5f, -4.99f, 0.17f),
									Transformation.Interpolations.CUBIC)))
			.addBoneAnimation("hood",
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(1f, AnimationHelper.createRotationalVector(-3.89f, 0f, 0f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(1.125f, AnimationHelper.createRotationalVector(-10f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(1.25f, AnimationHelper.createRotationalVector(-3.89f, 0f, 0f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(2f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("lefthand",
					new Transformation(Transformation.Targets.TRANSLATE,
							new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(0.5834334f, AnimationHelper.createTranslationalVector(0f, 0.75f, 0f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(0.75f, AnimationHelper.createTranslationalVector(0f, 0.75f, 0f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(1.1676667f, AnimationHelper.createTranslationalVector(0f, 0.75f, -1f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(2f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.CUBIC)))
			.addBoneAnimation("lefthand",
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0f, AnimationHelper.createRotationalVector(-2.5f, -7.5f, 0f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(0.875f, AnimationHelper.createRotationalVector(-82.82f, -14.82f, 1.67f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(1.0834333f, AnimationHelper.createRotationalVector(-86.8f, -32.16f, -0.87f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(1.1676667f, AnimationHelper.createRotationalVector(-94.44f, 27.76f, 2.26f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(2f, AnimationHelper.createRotationalVector(-2.5f, -7.5f, 0f),
									Transformation.Interpolations.CUBIC)))
			.addBoneAnimation("lefthand",
					new Transformation(Transformation.Targets.SCALE,
							new Keyframe(0f, AnimationHelper.createScalingVector(1f, 1f, 1f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(1.1676667f, AnimationHelper.createScalingVector(1f, 1.12f, 1f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(2f, AnimationHelper.createScalingVector(1f, 1f, 1f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(4f, AnimationHelper.createScalingVector(1f, 1f, 1f),
									Transformation.Interpolations.CUBIC)))
			.addBoneAnimation("righthand",
					new Transformation(Transformation.Targets.TRANSLATE,
							new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(0.5834334f, AnimationHelper.createTranslationalVector(0f, 1f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(2f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.CUBIC)))
			.addBoneAnimation("righthand",
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 5f, 0f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(1.0416767f, AnimationHelper.createRotationalVector(13.26f, 16.94f, 2.55f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(1.4167667f, AnimationHelper.createRotationalVector(-1.74f, 16.94f, 2.55f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(2f, AnimationHelper.createRotationalVector(0f, 5f, 0f),
									Transformation.Interpolations.CUBIC)))
			.addBoneAnimation("rightleg",
					new Transformation(Transformation.Targets.TRANSLATE,
							new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(0.5834334f, AnimationHelper.createTranslationalVector(0f, 0.5f, 0f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(2f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.CUBIC)))
			.addBoneAnimation("rightleg",
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0f, AnimationHelper.createRotationalVector(0.22f, 5f, 2.51f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(2f, AnimationHelper.createRotationalVector(0.22f, 5f, 2.51f),
									Transformation.Interpolations.CUBIC)))
			.addBoneAnimation("rightleg",
					new Transformation(Transformation.Targets.SCALE,
							new Keyframe(0f, AnimationHelper.createScalingVector(1f, 1f, 1f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.5834334f, AnimationHelper.createScalingVector(1f, 1.05f, 1f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(2f, AnimationHelper.createScalingVector(1f, 1f, 1f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("leftleg",
					new Transformation(Transformation.Targets.TRANSLATE,
							new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(0.5834334f, AnimationHelper.createTranslationalVector(0f, 0.5f, 0f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(2f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.CUBIC)))
			.addBoneAnimation("leftleg",
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0f, AnimationHelper.createRotationalVector(0f, -5f, 0f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(2f, AnimationHelper.createRotationalVector(0f, -5f, 0f),
									Transformation.Interpolations.CUBIC)))
			.addBoneAnimation("leftleg",
					new Transformation(Transformation.Targets.SCALE,
							new Keyframe(0f, AnimationHelper.createScalingVector(1f, 1f, 1f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.5834334f, AnimationHelper.createScalingVector(1f, 1.05f, 1f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(2f, AnimationHelper.createScalingVector(1f, 1f, 1f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("torso",
					new Transformation(Transformation.Targets.TRANSLATE,
							new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(0.5834334f, AnimationHelper.createTranslationalVector(0f, 0.8f, 0f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(1.9167667f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.CUBIC)))
			.addBoneAnimation("torso",
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0f, AnimationHelper.createRotationalVector(0f, -5f, 0f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(1.9167667f, AnimationHelper.createRotationalVector(0f, -5f, 0f),
									Transformation.Interpolations.CUBIC)))
			.addBoneAnimation("torso",
					new Transformation(Transformation.Targets.SCALE,
							new Keyframe(0.5834334f, AnimationHelper.createScalingVector(1f, 1.08f, 1f),
									Transformation.Interpolations.CUBIC)))
			.addBoneAnimation("head_eye",
					new Transformation(Transformation.Targets.TRANSLATE,
							new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0.25f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(2f, AnimationHelper.createTranslationalVector(0f, 0f, 0.25f),
									Transformation.Interpolations.LINEAR))).build();
	public static final Animation ANGRYIN = Animation.Builder.create(1f)
			.addBoneAnimation("eyeballs",
					new Transformation(Transformation.Targets.TRANSLATE,
							new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.75f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("eyeballs",
					new Transformation(Transformation.Targets.SCALE,
							new Keyframe(0f, AnimationHelper.createScalingVector(1f, 1f, 1f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.75f, AnimationHelper.createScalingVector(1f, 0.88f, 1f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("Reyeball",
					new Transformation(Transformation.Targets.TRANSLATE,
							new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.75f, AnimationHelper.createTranslationalVector(-0.1f, 0f, 0f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("Leyeball",
					new Transformation(Transformation.Targets.TRANSLATE,
							new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.75f, AnimationHelper.createTranslationalVector(0.1f, 0f, 0f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("Reyebrow",
					new Transformation(Transformation.Targets.TRANSLATE,
							new Keyframe(0.75f, AnimationHelper.createTranslationalVector(0f, 0f, -0.02f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("Reyebrow",
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 360f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.75f, AnimationHelper.createRotationalVector(0f, 0f, 372f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("Leyebrow",
					new Transformation(Transformation.Targets.TRANSLATE,
							new Keyframe(0.75f, AnimationHelper.createTranslationalVector(0f, 0f, -0.02f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("Leyebrow",
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, -0.75f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.75f, AnimationHelper.createRotationalVector(0f, 0f, -10.75f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("head_eye",
					new Transformation(Transformation.Targets.TRANSLATE,
							new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0.25f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(1f, AnimationHelper.createTranslationalVector(0f, 0f, 0.25f),
									Transformation.Interpolations.LINEAR))).build();
	public static final Animation ANGRYOUT = Animation.Builder.create(1f)
			.addBoneAnimation("eyeballs",
					new Transformation(Transformation.Targets.TRANSLATE,
							new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.75f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("eyeballs",
					new Transformation(Transformation.Targets.SCALE,
							new Keyframe(0f, AnimationHelper.createScalingVector(1f, 0.88f, 1f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.75f, AnimationHelper.createScalingVector(1f, 1f, 1f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("Reyeball",
					new Transformation(Transformation.Targets.TRANSLATE,
							new Keyframe(0f, AnimationHelper.createTranslationalVector(-0.1f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.75f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("Leyeball",
					new Transformation(Transformation.Targets.TRANSLATE,
							new Keyframe(0f, AnimationHelper.createTranslationalVector(0.1f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.75f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("Reyebrow",
					new Transformation(Transformation.Targets.TRANSLATE,
							new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, -0.02f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("Reyebrow",
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 372f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.75f, AnimationHelper.createRotationalVector(0f, 0f, 360f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("Leyebrow",
					new Transformation(Transformation.Targets.TRANSLATE,
							new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, -0.02f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("Leyebrow",
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, -10.75f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.75f, AnimationHelper.createRotationalVector(0f, 0f, -0.75f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("head_eye",
					new Transformation(Transformation.Targets.TRANSLATE,
							new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0.25f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(1f, AnimationHelper.createTranslationalVector(0f, 0f, 0.25f),
									Transformation.Interpolations.LINEAR))).build();
	public static final Animation NOW_I_CAN_YOU = Animation.Builder.create(1.5f)
			.addBoneAnimation("torso",
					new Transformation(Transformation.Targets.TRANSLATE,
							new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.75f, AnimationHelper.createTranslationalVector(0f, 0f, -0.5f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("torso",
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.75f, AnimationHelper.createRotationalVector(12.5f, 0f, 0f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("head",
					new Transformation(Transformation.Targets.TRANSLATE,
							new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(1f, AnimationHelper.createTranslationalVector(0f, 0f, -0.5f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("head",
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.75f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(1f, AnimationHelper.createRotationalVector(0f, 0f, 10f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(1.25f, AnimationHelper.createRotationalVector(0f, 0f, 15f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("lefthand",
					new Transformation(Transformation.Targets.TRANSLATE,
							new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.75f, AnimationHelper.createTranslationalVector(0f, 0f, -1.5f),
									Transformation.Interpolations.CUBIC)))
			.addBoneAnimation("lefthand",
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.75f, AnimationHelper.createRotationalVector(-5f, 0f, 0f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(2f, AnimationHelper.createRotationalVector(-2.5f, 0f, 0f),
									Transformation.Interpolations.CUBIC)))
			.addBoneAnimation("righthand",
					new Transformation(Transformation.Targets.TRANSLATE,
							new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.75f, AnimationHelper.createTranslationalVector(0f, 0f, -1.5f),
									Transformation.Interpolations.CUBIC)))
			.addBoneAnimation("righthand",
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.75f, AnimationHelper.createRotationalVector(10f, 0f, 0f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(2f, AnimationHelper.createRotationalVector(7.5f, 0f, 0f),
									Transformation.Interpolations.CUBIC)))
			.addBoneAnimation("rightleg",
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.25f, AnimationHelper.createRotationalVector(0.22f, 5f, 2.51f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("leftleg",
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.25f, AnimationHelper.createRotationalVector(0.22f, -5f, -2.51f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("eyeballs",
					new Transformation(Transformation.Targets.TRANSLATE,
							new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("eyeballs",
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("Reyeball",
					new Transformation(Transformation.Targets.TRANSLATE,
							new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.75f, AnimationHelper.createTranslationalVector(0.08f, 0f, 0f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(1.5f, AnimationHelper.createTranslationalVector(-0.25f, 0f, 0f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("Reyeball",
					new Transformation(Transformation.Targets.SCALE,
							new Keyframe(0f, AnimationHelper.createScalingVector(1f, 1f, 1f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(1.5f, AnimationHelper.createScalingVector(0.8f, 0.39f, 1f),
									Transformation.Interpolations.CUBIC)))
			.addBoneAnimation("Leyeball",
					new Transformation(Transformation.Targets.TRANSLATE,
							new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.75f, AnimationHelper.createTranslationalVector(-0.08f, 0f, 0f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(1.5f, AnimationHelper.createTranslationalVector(0.25f, 0f, 0f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("Leyeball",
					new Transformation(Transformation.Targets.SCALE,
							new Keyframe(0f, AnimationHelper.createScalingVector(1f, 1f, 1f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(1.5f, AnimationHelper.createScalingVector(0.8f, 0.39f, 1f),
									Transformation.Interpolations.CUBIC)))
			.addBoneAnimation("Reyebrow",
					new Transformation(Transformation.Targets.TRANSLATE,
							new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(1.1676667f, AnimationHelper.createTranslationalVector(0f, 0.2f, 0f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("Reyebrow",
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(1.1676667f, AnimationHelper.createRotationalVector(0f, 0f, -2.5f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("Leyebrow",
					new Transformation(Transformation.Targets.TRANSLATE,
							new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(1.1676667f, AnimationHelper.createTranslationalVector(0f, 0.2f, 0f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("Leyebrow",
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(1.1676667f, AnimationHelper.createRotationalVector(0f, 0f, 2.5f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("head_eye",
					new Transformation(Transformation.Targets.SCALE,
							new Keyframe(0f, AnimationHelper.createScalingVector(1f, 1f, 0.98f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(1.5f, AnimationHelper.createScalingVector(1f, 1f, 0.98f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("up",
					new Transformation(Transformation.Targets.TRANSLATE,
							new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.20834334f, AnimationHelper.createTranslationalVector(0f, -1f, 0f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(0.4167667f, AnimationHelper.createTranslationalVector(0f, 0.12f, 0f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(1.5f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("down",
					new Transformation(Transformation.Targets.TRANSLATE,
							new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.20834334f, AnimationHelper.createTranslationalVector(0f, 1f, 0f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(0.4167667f, AnimationHelper.createTranslationalVector(0f, -0.12f, 0f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(1.5f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR))).build();
	public static final Animation BLINK = Animation.Builder.create(1f)
			.addBoneAnimation("head_eye",
					new Transformation(Transformation.Targets.SCALE,
							new Keyframe(0f, AnimationHelper.createScalingVector(1f, 1f, 0.98f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(1f, AnimationHelper.createScalingVector(1f, 1f, 0.98f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("up",
					new Transformation(Transformation.Targets.TRANSLATE,
							new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.375f, AnimationHelper.createTranslationalVector(0f, -1f, 0f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(0.625f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.CUBIC)))
			.addBoneAnimation("down",
					new Transformation(Transformation.Targets.TRANSLATE,
							new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.375f, AnimationHelper.createTranslationalVector(0f, 1f, 0f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(0.625f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.CUBIC))).build();
}